### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Banstein** [cynthiainga/leaderboard#4]
Hi @cynthiainga, Good job so far for completing the project,I have some suggestions for you.

-  I like the animation of the refresh button, I suggest changing the animation to be when it's active instead of being animating by default.

====

by Dagic,
-  Add some interaction when the data are loading and saving to the servers. When they are loading just say Loading or show a spinner and also when data are saved just show the items are saving.

**Comment by cynthiainga** [comment]
Thanks guys for the feedback.
