### ISSUE TITLE
Form Data validation.

### ISSUE THREAD

**Issue by Nemwel-Boniface** [cynthiainga/leaderboard#5]
## Hello @cynthiainga  :wave: :wave: 

You did a great job on your Leader board project. I like the styling and the animations as well. I however have the following suggested changes to make your project even better:

![](https://media.giphy.com/media/xThta99fqDHWhicxVe/giphy.gif)
## :recycle: Suggested changes :recycle: 

- [ ] I like the animation on the refresh button. I however would like to echo [This issue](https://github.com/cynthiainga/leaderboard/issues/4#issue-1159329210). It would be great if the refresh animation would not be there by default as it is.
- [ ] Great job sorting the data. It would be great if you included some form-data validation. You could use the following HTML form validations I recommend:

  1.  Using ```minlength``` and ```maxlength``` for validating the length of the user's name. i put "```hellothisisaverylongtest```" and it accepted it something I feel should be changed.
  2. Using ```min``` and ```max``` to give your users the minimum and maximum number they can input. I already found someone tried inputting a very long number and it just got accepted.

***Remember garbage in garbage out. This is where Form validation helps to put the data input in check***

You can leave me a comment incase you have any questions.

#Happycoding

**Comment by cynthiainga** [comment]
Thanks, @Nemwel-Boniface. I add the `maxlength` and `minlength` for the validation form, and I change the animation for the refresh button, now the animation is active just when we refresh the page.

**Comment by Nemwel-Boniface** [comment]
Great job implementing the changes @cynthiainga .
all the best in your next projects and #happycoding

**Comment by cynthiainga** [comment]
:pray:  all the best to you too

### happycoding :man_technologist:
